import type { Problem, Tag, ImageAsset, Paper, ExportJob } from './types';

// Mock 标签数据
export const mockTags: Tag[] = [
  { id: 't1', name: '积分', category: 'topic', color: '#0F766E', problemCount: 128 },
  { id: 't2', name: '定积分', category: 'topic', color: '#0F766E', problemCount: 86 },
  { id: 't3', name: '三角函数', category: 'topic', color: '#0891B2', problemCount: 156 },
  { id: 't4', name: '数列', category: 'topic', color: '#7C3AED', problemCount: 92 },
  { id: 't5', name: '数学归纳法', category: 'topic', color: '#7C3AED', problemCount: 45 },
  { id: 't6', name: '导数', category: 'topic', color: '#DC2626', problemCount: 178 },
  { id: 't7', name: '概率统计', category: 'topic', color: '#F59E0B', problemCount: 134 },
  { id: 't8', name: '解析几何', category: 'topic', color: '#10B981', problemCount: 167 },
  { id: 't9', name: '立体几何', category: 'topic', color: '#6366F1', problemCount: 89 },
  { id: 't10', name: '函数', category: 'topic', color: '#EC4899', problemCount: 245 },
  { id: 't11', name: '北京高考', category: 'source', color: '#EF4444', problemCount: 56 },
  { id: 't12', name: '全国卷', category: 'source', color: '#EF4444', problemCount: 128 },
  { id: 't13', name: '模拟题', category: 'source', color: '#F97316', problemCount: 234 },
  { id: 't14', name: '重点', category: 'custom', color: '#FBBF24', problemCount: 67 },
  { id: 't15', name: '易错', category: 'custom', color: '#F87171', problemCount: 45 },
  { id: 't16', name: '向量', category: 'topic', color: '#14B8A6', problemCount: 78 },
  { id: 't17', name: '不等式', category: 'topic', color: '#8B5CF6', problemCount: 112 },
  { id: 't18', name: '集合', category: 'topic', color: '#06B6D4', problemCount: 56 },
  { id: 't19', name: '复数', category: 'topic', color: '#84CC16', problemCount: 34 },
  { id: 't20', name: '排列组合', category: 'topic', color: '#F472B6', problemCount: 89 },
];

// Mock 题目数据
export const mockProblems: Problem[] = [
  {
    id: 'p1',
    code: 'P-2024-0001',
    latex: '求定积分 \\(\\int_0^1 x^2 \\,dx\\) 的值。',
    answerLatex: '\\(\\dfrac{1}{3}\\)',
    solutionLatex: '根据定积分的定义，\\(\\int_0^1 x^2 \\,dx = \\left[\\dfrac{x^3}{3}\\right]_0^1 = \\dfrac{1}{3} - 0 = \\dfrac{1}{3}\\)。',
    type: 'solve',
    difficulty: 'easy',
    subjectiveScore: 3,
    subject: '数学',
    grade: '高三',
    tagIds: ['t1', 't2'],
    imageIds: [],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p2',
    code: 'P-2024-0002',
    latex: '在 \\(\\triangle ABC\\) 中，已知 \\(a=2\\)，\\(b=\\sqrt{3}\\)，\\(\\angle A = 60^\\circ\\)，求 \\(\\angle B\\)。',
    answerLatex: '\\(\\angle B = 45^\\circ\\) 或 \\(\\angle B = 135^\\circ\\)',
    solutionLatex: '由正弦定理 \\(\\dfrac{a}{\\sin A} = \\dfrac{b}{\\sin B}\\)，代入得 \\(\\sin B = \\dfrac{b \\sin A}{a} = \\dfrac{\\sqrt{3} \\cdot \\frac{\\sqrt{3}}{2}}{2} = \\dfrac{3}{4}\\)。',
    type: 'solve',
    difficulty: 'medium',
    subjectiveScore: 5,
    subject: '数学',
    grade: '高二',
    source: '2023 北京高考',
    tagIds: ['t3', 't11'],
    imageIds: [],
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    version: 2,
    isDeleted: false,
  },
  {
    id: 'p3',
    code: 'P-2024-0003',
    latex: '证明：对任意正整数 \\(n\\)，\\(\\sum_{k=1}^n k^3 = \\left(\\dfrac{n(n+1)}{2}\\right)^2\\)。',
    answerLatex: '证明见解析',
    solutionLatex: '使用数学归纳法证明：\n1. 当 \\(n=1\\) 时，左边 = 1，右边 = 1，成立。\n2. 假设 \\(n=k\\) 时成立，则 \\(n=k+1\\) 时...',
    type: 'proof',
    difficulty: 'hard',
    subjectiveScore: 8,
    subject: '数学',
    grade: '高三',
    tagIds: ['t4', 't5'],
    imageIds: ['img1'],
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p4',
    code: 'P-2024-0004',
    latex: '设函数 \\(f(x) = e^x - ax\\)，讨论 \\(f(x)\\) 的单调性。',
    type: 'solve',
    difficulty: 'medium',
    subjectiveScore: 6,
    subject: '数学',
    grade: '高三',
    tagIds: ['t6', 't10'],
    imageIds: [],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p5',
    code: 'P-2024-0005',
    latex: '已知随机变量 \\(X\\) 服从正态分布 \\(N(2, 4)\\)，求 \\(P(X > 4)\\)。',
    type: 'solve',
    difficulty: 'easy',
    subjectiveScore: 4,
    subject: '数学',
    grade: '高二',
    tagIds: ['t7'],
    imageIds: [],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p6',
    code: 'P-2024-0006',
    latex: '已知椭圆 \\(\\dfrac{x^2}{a^2} + \\dfrac{y^2}{b^2} = 1\\) (\\(a > b > 0\\)) 的离心率为 \\(\\dfrac{\\sqrt{2}}{2}\\)，求 \\(a\\) 与 \\(b\\) 的关系。',
    type: 'solve',
    difficulty: 'medium',
    subjectiveScore: 5,
    subject: '数学',
    grade: '高三',
    tagIds: ['t8'],
    imageIds: ['img1', 'img2'],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p7',
    code: 'P-2024-0007',
    latex: '如图，在正方体 \\(ABCD-A_1B_1C_1D_1\\) 中，求直线 \\(A_1C\\) 与平面 \\(BDD_1B_1\\) 所成的角。',
    type: 'solve',
    difficulty: 'hard',
    subjectiveScore: 7,
    subject: '数学',
    grade: '高三',
    tagIds: ['t9', 't16'],
    imageIds: ['img1', 'img3'],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p8',
    code: 'P-2024-0008',
    latex: '已知函数 \\(f(x) = \\ln x - \\dfrac{1}{2}x^2 + x\\)，求 \\(f(x)\\) 的极值。',
    type: 'solve',
    difficulty: 'medium',
    subjectiveScore: 6,
    subject: '数学',
    grade: '高三',
    tagIds: ['t6', 't10'],
    imageIds: [],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p9',
    code: 'P-2024-0009',
    latex: '若 \\(a, b \\in \\mathbb{R}^+\\) 且 \\(a + b = 1\\)，求 \\(\\dfrac{1}{a} + \\dfrac{4}{b}\\) 的最小值。',
    type: 'solve',
    difficulty: 'medium',
    subjectiveScore: 5,
    subject: '数学',
    grade: '高二',
    tagIds: ['t17'],
    imageIds: [],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p10',
    code: 'P-2024-0010',
    latex: '设集合 \\(A = \\{x | x^2 - 3x + 2 < 0\\}\\)，\\(B = \\{x | x > 1\\}\\)，求 \\(A \\cap B\\)。',
    type: 'solve',
    difficulty: 'easy',
    subjectiveScore: 2,
    subject: '数学',
    grade: '高一',
    tagIds: ['t18'],
    imageIds: [],
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p11',
    code: 'P-2024-0011',
    latex: '计算复数 \\(\\dfrac{(1+i)^2}{1-i}\\) 的值。',
    type: 'solve',
    difficulty: 'easy',
    subjectiveScore: 2,
    subject: '数学',
    grade: '高二',
    tagIds: ['t19'],
    imageIds: [],
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p12',
    code: 'P-2024-0012',
    latex: '从 5 名男生和 3 名女生中选 4 人参加比赛，要求至少有 1 名女生，共有多少种选法？',
    type: 'solve',
    difficulty: 'easy',
    subjectiveScore: 3,
    subject: '数学',
    grade: '高二',
    tagIds: ['t20', 't7'],
    imageIds: [],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p13',
    code: 'P-2024-0013',
    latex: '设等差数列 \\(\\{a_n\\}\\) 的前 \\(n\\) 项和为 \\(S_n\\)，若 \\(a_3 = 7\\)，\\(S_4 = 24\\)，求数列的通项公式。',
    type: 'solve',
    difficulty: 'medium',
    subjectiveScore: 5,
    subject: '数学',
    grade: '高二',
    tagIds: ['t4'],
    imageIds: [],
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p14',
    code: 'P-2024-0014',
    latex: '求函数 \\(y = \\sin 2x + \\cos 2x\\) 的最大值及取得最大值时 \\(x\\) 的取值集合。',
    type: 'solve',
    difficulty: 'medium',
    subjectiveScore: 5,
    subject: '数学',
    grade: '高一',
    tagIds: ['t3', 't10'],
    imageIds: [],
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p15',
    code: 'P-2024-0015',
    latex: '在平面直角坐标系中，向量 \\(\\vec{a} = (1, 2)\\)，\\(\\vec{b} = (3, -1)\\)，求 \\(\\vec{a} \\cdot \\vec{b}\\) 和 \\(|\\vec{a} + \\vec{b}|\\)。',
    type: 'solve',
    difficulty: 'easy',
    subjectiveScore: 3,
    subject: '数学',
    grade: '高一',
    tagIds: ['t16'],
    imageIds: [],
    createdAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p16',
    code: 'P-2024-0016',
    latex: '设 \\(f(x) = |x - 1| + |x + 2|\\)，求 \\(f(x)\\) 的最小值。',
    type: 'solve',
    difficulty: 'medium',
    subjectiveScore: 4,
    subject: '数学',
    grade: '高一',
    tagIds: ['t10', 't17'],
    imageIds: [],
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p17',
    code: 'P-2024-0017',
    latex: '已知抛物线 \\(y^2 = 4x\\) 的焦点为 \\(F\\)，点 \\(P\\) 在抛物线上且 \\(|PF| = 5\\)，求点 \\(P\\) 的坐标。',
    type: 'solve',
    difficulty: 'medium',
    subjectiveScore: 5,
    subject: '数学',
    grade: '高三',
    tagIds: ['t8'],
    imageIds: [],
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p18',
    code: 'P-2024-0018',
    latex: '求 \\(\\lim_{n \\to \\infty} \\dfrac{1 + 2 + 3 + \\cdots + n}{n^2}\\) 的值。',
    type: 'solve',
    difficulty: 'easy',
    subjectiveScore: 3,
    subject: '数学',
    grade: '高三',
    tagIds: ['t4'],
    imageIds: [],
    createdAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p19',
    code: 'P-2024-0019',
    latex: '设 \\(f(x)\\) 是定义在 \\(\\mathbb{R}\\) 上的奇函数，当 \\(x > 0\\) 时，\\(f(x) = x^2 - 2x\\)。求 \\(f(-3)\\)。',
    type: 'solve',
    difficulty: 'easy',
    subjectiveScore: 3,
    subject: '数学',
    grade: '高一',
    tagIds: ['t10'],
    imageIds: [],
    createdAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p20',
    code: 'P-2024-0020',
    latex: '已知数列 \\(\\{a_n\\}\\) 满足 \\(a_1 = 1\\)，\\(a_{n+1} = 2a_n + 1\\)，求通项公式 \\(a_n\\)。',
    type: 'solve',
    difficulty: 'medium',
    subjectiveScore: 6,
    subject: '数学',
    grade: '高二',
    tagIds: ['t4'],
    imageIds: [],
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p21',
    code: 'P-2024-0021',
    latex: '证明：对于任意的正整数 \\(n\\)，\\(n^3 - n\\) 能被 6 整除。',
    type: 'proof',
    difficulty: 'medium',
    subjectiveScore: 5,
    subject: '数学',
    grade: '高一',
    tagIds: ['t5'],
    imageIds: [],
    createdAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p22',
    code: 'P-2024-0022',
    latex: '已知 \\(\\sin\\alpha + \\cos\\alpha = \\dfrac{1}{5}\\)，\\(\\alpha \\in (0, \\pi)\\)，求 \\(\\tan\\alpha\\) 的值。',
    type: 'solve',
    difficulty: 'hard',
    subjectiveScore: 7,
    subject: '数学',
    grade: '高一',
    tagIds: ['t3'],
    imageIds: [],
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p23',
    code: 'P-2024-0023',
    latex: '在国际数学奥林匹克中，证明对于任意正整数 \\(n\\)，存在 \\(n\\) 个连续正整数，使得它们都是合数。',
    type: 'proof',
    difficulty: 'olympiad',
    subjectiveScore: 10,
    subject: '数学',
    grade: '高三',
    tagIds: ['t5', 't14'],
    imageIds: [],
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
  {
    id: 'p24',
    code: 'P-2024-0024',
    latex: '设 \\(a, b, c\\) 为正实数且 \\(abc = 1\\)，证明 \\(\\dfrac{1}{a^3(b+c)} + \\dfrac{1}{b^3(c+a)} + \\dfrac{1}{c^3(a+b)} \\geq \\dfrac{3}{2}\\)。',
    type: 'proof',
    difficulty: 'olympiad',
    subjectiveScore: 9,
    subject: '数学',
    grade: '高三',
    tagIds: ['t17', 't14'],
    imageIds: [],
    createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    version: 1,
    isDeleted: false,
  },
];

// Mock 图像数据
export const mockImages: ImageAsset[] = [
  {
    id: 'img1',
    filename: 'cube-diagram.png',
    mime: 'image/png',
    size: 45678,
    width: 800,
    height: 600,
    url: 'https://placehold.co/800x600/e2e8f0/64748b?text=Cube+Diagram',
    thumbnailUrl: 'https://placehold.co/200x150/e2e8f0/64748b?text=Cube',
    tagIds: ['t9'],
    linkedProblemIds: ['p3', 'p6', 'p7'],
    description: '共享的立体几何示意图',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    isDeleted: false,
  },
  {
    id: 'img2',
    filename: 'ellipse.png',
    mime: 'image/png',
    size: 34567,
    width: 600,
    height: 400,
    url: 'https://placehold.co/600x400/e2e8f0/64748b?text=Ellipse',
    thumbnailUrl: 'https://placehold.co/200x133/e2e8f0/64748b?text=Ellipse',
    tagIds: ['t8'],
    linkedProblemIds: ['p6'],
    description: '椭圆示意图',
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    isDeleted: false,
  },
  {
    id: 'img3',
    filename: 'solid-geometry.png',
    mime: 'image/png',
    size: 56789,
    width: 700,
    height: 700,
    url: 'https://placehold.co/700x700/e2e8f0/64748b?text=Solid+Geometry',
    thumbnailUrl: 'https://placehold.co/200x200/e2e8f0/64748b?text=Solid',
    tagIds: ['t9'],
    linkedProblemIds: ['p7'],
    description: '立体几何图形',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    isDeleted: false,
  },
  {
    id: 'img4',
    filename: 'coordinate-system.png',
    mime: 'image/png',
    size: 23456,
    width: 500,
    height: 500,
    url: 'https://placehold.co/500x500/e2e8f0/64748b?text=Coordinate',
    thumbnailUrl: 'https://placehold.co/200x200/e2e8f0/64748b?text=Coord',
    tagIds: ['t8', 't10'],
    linkedProblemIds: ['p8'],
    description: '坐标系背景图',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    isDeleted: false,
  },
  {
    id: 'img5',
    filename: 'triangle-abc.png',
    mime: 'image/png',
    size: 34567,
    width: 600,
    height: 450,
    url: 'https://placehold.co/600x450/e2e8f0/64748b?text=Triangle',
    thumbnailUrl: 'https://placehold.co/200x150/e2e8f0/64748b?text=Triangle',
    tagIds: ['t3', 't16'],
    linkedProblemIds: ['p2', 'p14'],
    description: '三角函数辅助图',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    isDeleted: false,
  },
  {
    id: 'img6',
    filename: 'function-graph.jpg',
    mime: 'image/jpeg',
    size: 45678,
    width: 800,
    height: 500,
    url: 'https://placehold.co/800x500/e2e8f0/64748b?text=Function+Graph',
    thumbnailUrl: 'https://placehold.co/200x125/e2e8f0/64748b?text=Graph',
    tagIds: ['t6', 't10'],
    linkedProblemIds: ['p4', 'p8'],
    description: '函数图像示意',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    isDeleted: false,
  },
  {
    id: 'img7',
    filename: 'probability-tree.png',
    mime: 'image/png',
    size: 56789,
    width: 700,
    height: 800,
    url: 'https://placehold.co/700x800/e2e8f0/64748b?text=Probability+Tree',
    thumbnailUrl: 'https://placehold.co/175x200/e2e8f0/64748b?text=Tree',
    tagIds: ['t7', 't20'],
    linkedProblemIds: ['p12'],
    description: '概率树状图',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    isDeleted: false,
  },
  {
    id: 'img8',
    filename: 'vector-diagram.webp',
    mime: 'image/webp',
    size: 23456,
    width: 600,
    height: 600,
    url: 'https://placehold.co/600x600/e2e8f0/64748b?text=Vector',
    thumbnailUrl: 'https://placehold.co/200x200/e2e8f0/64748b?text=Vector',
    tagIds: ['t16', 't9'],
    linkedProblemIds: ['p7'],
    description: '向量关系示意',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isDeleted: false,
  },
  {
    id: 'img9',
    filename: 'parabola.png',
    mime: 'image/png',
    size: 34567,
    width: 640,
    height: 480,
    url: 'https://placehold.co/640x480/e2e8f0/64748b?text=Parabola',
    thumbnailUrl: 'https://placehold.co/200x150/e2e8f0/64748b?text=Parabola',
    tagIds: ['t8', 't10'],
    linkedProblemIds: ['p4'],
    description: '抛物线图像',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isDeleted: false,
  },
  {
    id: 'img10',
    filename: 'sphere.png',
    mime: 'image/png',
    size: 45678,
    width: 500,
    height: 500,
    url: 'https://placehold.co/500x500/e2e8f0/64748b?text=Sphere',
    thumbnailUrl: 'https://placehold.co/200x200/e2e8f0/64748b?text=Sphere',
    tagIds: ['t9'],
    linkedProblemIds: [],
    description: '球体与截面示意',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isDeleted: false,
  },
  {
    id: 'img11',
    filename: 'matrix-table.png',
    mime: 'image/png',
    size: 23456,
    width: 400,
    height: 300,
    url: 'https://placehold.co/400x300/e2e8f0/64748b?text=Matrix',
    thumbnailUrl: 'https://placehold.co/200x150/e2e8f0/64748b?text=Matrix',
    tagIds: ['t4'],
    linkedProblemIds: ['p13'],
    description: '矩阵与表格素材',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    isDeleted: false,
  },
  {
    id: 'img12',
    filename: 'circle-theorem.png',
    mime: 'image/png',
    size: 34567,
    width: 550,
    height: 550,
    url: 'https://placehold.co/550x550/e2e8f0/64748b?text=Circle+Theorem',
    thumbnailUrl: 'https://placehold.co/200x200/e2e8f0/64748b?text=Circle',
    tagIds: ['t3', 't14'],
    linkedProblemIds: [],
    description: '圆幂与弦切角图',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    isDeleted: false,
  },
];

// Mock 试卷数据 (扩展格式用于列表页)
export interface MockPaperListItem {
  id: string;
  title: string;
  description?: string;
  status: 'draft' | 'completed' | 'review';
  problemCount: number;
  totalScore: number;
  createdAt: string;
  updatedAt: string;
}

export const mockPapers: MockPaperListItem[] = [
  {
    id: 'paper1',
    title: '2024年高三数学期中考试',
    description: '涵盖函数、导数、三角函数等知识点',
    status: 'completed',
    problemCount: 22,
    totalScore: 150,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'paper2',
    title: '高二数学周测（第3周）',
    description: '数列与等差等比数列',
    status: 'completed',
    problemCount: 15,
    totalScore: 100,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'paper3',
    title: '函数专题练习',
    description: '函数的性质、图像变换',
    status: 'draft',
    problemCount: 8,
    totalScore: 60,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'paper4',
    title: '解析几何综合测试',
    description: '椭圆、双曲线、抛物线',
    status: 'review',
    problemCount: 12,
    totalScore: 100,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'paper5',
    title: '三角函数单元测试',
    status: 'draft',
    problemCount: 5,
    totalScore: 40,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock 试卷模板
export interface MockTemplate {
  id: string;
  name: string;
  description?: string;
}

export const mockTemplates: MockTemplate[] = [
  { id: 'tmpl1', name: '标准高考试卷模板', description: '22题，150分' },
  { id: 'tmpl2', name: '周测模板', description: '15题，100分' },
  { id: 'tmpl3', name: '专题练习模板', description: '10题，60分' },
];

// Mock 导出任务数据
export const mockExportJobs: ExportJob[] = [
  {
    id: 'e1',
    paperId: 'paper1',
    paperTitle: '2024年高三期中考试卷',
    format: 'pdf',
    variant: 'both',
    status: 'done',
    downloadUrl: '#',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'e2',
    paperId: 'paper2',
    paperTitle: '高二数学周测',
    format: 'latex',
    variant: 'student',
    status: 'done',
    downloadUrl: '#',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'e3',
    paperId: 'paper1',
    paperTitle: '函数专题练习',
    format: 'pdf',
    variant: 'answer',
    status: 'processing',
    progress: 65,
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'e4',
    paperId: 'paper1',
    paperTitle: '三角函数测验',
    format: 'pdf',
    variant: 'both',
    status: 'failed',
    errorMessage: 'LaTeX 编译错误：未定义的命令 \\mycmd',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// 辅助函数：格式化相对时间
export function formatRelativeTime(dateString: string): string {
  const date = new Date(dateString);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / (1000 * 60));
  const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  if (diffMins < 60) {
    return `${diffMins} 分钟前`;
  } else if (diffHours < 24) {
    return `${diffHours} 小时前`;
  } else if (diffDays < 7) {
    return `${diffDays} 天前`;
  } else {
    return date.toLocaleDateString('zh-CN', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
    });
  }
}
