// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: exports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExportJob = `-- name: DeleteExportJob :exec
DELETE FROM export_jobs WHERE id = $1
`

func (q *Queries) DeleteExportJob(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteExportJob, id)
	return err
}

const getExportJobByID = `-- name: GetExportJobByID :one
SELECT id, paper_id, paper_title, format, variant, status, progress,
  download_path, error_message, created_at, started_at, completed_at, cancel_requested_at
FROM export_jobs
WHERE id = $1
`

func (q *Queries) GetExportJobByID(ctx context.Context, id string) (ExportJob, error) {
	row := q.db.QueryRow(ctx, getExportJobByID, id)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.PaperTitle,
		&i.Format,
		&i.Variant,
		&i.Status,
		&i.Progress,
		&i.DownloadPath,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
	)
	return i, err
}

const getExportJobsByPaperID = `-- name: GetExportJobsByPaperID :many
SELECT id, paper_id, paper_title, format, variant, status, progress,
  download_path, error_message, created_at, started_at, completed_at, cancel_requested_at
FROM export_jobs
WHERE paper_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetExportJobsByPaperID(ctx context.Context, paperID string) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, getExportJobsByPaperID, paperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportJob
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.PaperID,
			&i.PaperTitle,
			&i.Format,
			&i.Variant,
			&i.Status,
			&i.Progress,
			&i.DownloadPath,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CancelRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertExportJob = `-- name: InsertExportJob :one
INSERT INTO export_jobs (
  id, paper_id, paper_title, format, variant, status, progress, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, paper_id, paper_title, format, variant, status, progress,
  download_path, error_message, created_at, started_at, completed_at, cancel_requested_at
`

type InsertExportJobParams struct {
	ID         string
	PaperID    string
	PaperTitle string
	Format     string
	Variant    string
	Status     string
	Progress   int32
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertExportJob(ctx context.Context, arg InsertExportJobParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, insertExportJob,
		arg.ID,
		arg.PaperID,
		arg.PaperTitle,
		arg.Format,
		arg.Variant,
		arg.Status,
		arg.Progress,
		arg.CreatedAt,
	)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.PaperTitle,
		&i.Format,
		&i.Variant,
		&i.Status,
		&i.Progress,
		&i.DownloadPath,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
	)
	return i, err
}

const listExportJobs = `-- name: ListExportJobs :many
SELECT id, paper_id, paper_title, format, variant, status, progress,
  download_path, error_message, created_at, started_at, completed_at, cancel_requested_at
FROM export_jobs
ORDER BY created_at DESC
`

func (q *Queries) ListExportJobs(ctx context.Context) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, listExportJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportJob
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.PaperID,
			&i.PaperTitle,
			&i.Format,
			&i.Variant,
			&i.Status,
			&i.Progress,
			&i.DownloadPath,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CancelRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestExportCancellation = `-- name: RequestExportCancellation :exec
UPDATE export_jobs
SET cancel_requested_at = now()
WHERE id = $1
  AND status = 'processing'
`

func (q *Queries) RequestExportCancellation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, requestExportCancellation, id)
	return err
}

const updateExportJobStatus = `-- name: UpdateExportJobStatus :exec
UPDATE export_jobs SET
  status = $2,
  progress = $3,
  started_at = $4,
  completed_at = $5,
  error_message = $6,
  download_path = $7,
  cancel_requested_at = $8
WHERE id = $1
`

type UpdateExportJobStatusParams struct {
	ID                string
	Status            string
	Progress          int32
	StartedAt         pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	ErrorMessage      pgtype.Text
	DownloadPath      pgtype.Text
	CancelRequestedAt pgtype.Timestamptz
}

func (q *Queries) UpdateExportJobStatus(ctx context.Context, arg UpdateExportJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateExportJobStatus,
		arg.ID,
		arg.Status,
		arg.Progress,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.DownloadPath,
		arg.CancelRequestedAt,
	)
	return err
}
