// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: images.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countImages = `-- name: CountImages :one
SELECT count(*) FROM images
WHERE ($1::boolean = true OR deleted_at IS NULL)
`

func (q *Queries) CountImages(ctx context.Context, dollar_1 bool) (int64, error) {
	row := q.db.QueryRow(ctx, countImages, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteImageTags = `-- name: DeleteImageTags :exec
DELETE FROM image_tags WHERE image_id = $1
`

func (q *Queries) DeleteImageTags(ctx context.Context, imageID string) error {
	_, err := q.db.Exec(ctx, deleteImageTags, imageID)
	return err
}

const getImageByID = `-- name: GetImageByID :one
SELECT id, filename, mime, size_bytes, width, height, storage_path, thumbnail_path,
  description, parent_image_id, created_at, updated_at, deleted_at
FROM images
WHERE id = $1
`

func (q *Queries) GetImageByID(ctx context.Context, id string) (Image, error) {
	row := q.db.QueryRow(ctx, getImageByID, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Mime,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.Description,
		&i.ParentImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getImageLinkedProblemIDs = `-- name: GetImageLinkedProblemIDs :many
SELECT problem_id FROM problem_images WHERE image_id = $1
`

func (q *Queries) GetImageLinkedProblemIDs(ctx context.Context, imageID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getImageLinkedProblemIDs, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var problem_id string
		if err := rows.Scan(&problem_id); err != nil {
			return nil, err
		}
		items = append(items, problem_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImageTagIDs = `-- name: GetImageTagIDs :many
SELECT tag_id FROM image_tags WHERE image_id = $1
`

func (q *Queries) GetImageTagIDs(ctx context.Context, imageID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getImageTagIDs, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag_id string
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteImage = `-- name: HardDeleteImage :exec
DELETE FROM images WHERE id = $1
`

func (q *Queries) HardDeleteImage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, hardDeleteImage, id)
	return err
}

const insertImage = `-- name: InsertImage :one
INSERT INTO images (
  id, filename, mime, size_bytes, width, height, storage_path, thumbnail_path,
  description, parent_image_id, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8,
  $9, $10, $11, $12
)
RETURNING id, filename, mime, size_bytes, width, height, storage_path, thumbnail_path,
  description, parent_image_id, created_at, updated_at, deleted_at
`

type InsertImageParams struct {
	ID            string
	Filename      string
	Mime          string
	SizeBytes     int64
	Width         int32
	Height        int32
	StoragePath   string
	ThumbnailPath string
	Description   pgtype.Text
	ParentImageID pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) InsertImage(ctx context.Context, arg InsertImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, insertImage,
		arg.ID,
		arg.Filename,
		arg.Mime,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.StoragePath,
		arg.ThumbnailPath,
		arg.Description,
		arg.ParentImageID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Mime,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.Description,
		&i.ParentImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertImageTag = `-- name: InsertImageTag :exec
INSERT INTO image_tags (image_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertImageTagParams struct {
	ImageID string
	TagID   string
}

func (q *Queries) InsertImageTag(ctx context.Context, arg InsertImageTagParams) error {
	_, err := q.db.Exec(ctx, insertImageTag, arg.ImageID, arg.TagID)
	return err
}

const listImages = `-- name: ListImages :many
SELECT id, filename, mime, size_bytes, width, height, storage_path, thumbnail_path,
  description, parent_image_id, created_at, updated_at, deleted_at
FROM images
WHERE ($1::boolean = true OR deleted_at IS NULL)
ORDER BY created_at DESC
`

func (q *Queries) ListImages(ctx context.Context, dollar_1 bool) ([]Image, error) {
	rows, err := q.db.Query(ctx, listImages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Mime,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.StoragePath,
			&i.ThumbnailPath,
			&i.Description,
			&i.ParentImageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreImage = `-- name: RestoreImage :exec
UPDATE images SET deleted_at = NULL WHERE id = $1
`

func (q *Queries) RestoreImage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, restoreImage, id)
	return err
}

const softDeleteImage = `-- name: SoftDeleteImage :exec
UPDATE images SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteImage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteImage, id)
	return err
}

const updateImage = `-- name: UpdateImage :one
UPDATE images SET
  filename = $2,
  description = $3,
  updated_at = $4
WHERE id = $1
RETURNING id, filename, mime, size_bytes, width, height, storage_path, thumbnail_path,
  description, parent_image_id, created_at, updated_at, deleted_at
`

type UpdateImageParams struct {
	ID          string
	Filename    string
	Description pgtype.Text
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, updateImage,
		arg.ID,
		arg.Filename,
		arg.Description,
		arg.UpdatedAt,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Mime,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.Description,
		&i.ParentImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
