// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: papers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPapers = `-- name: CountPapers :one
SELECT count(*) FROM papers
WHERE ($1::boolean = true OR deleted_at IS NULL)
`

func (q *Queries) CountPapers(ctx context.Context, dollar_1 bool) (int64, error) {
	row := q.db.QueryRow(ctx, countPapers, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePaperItems = `-- name: DeletePaperItems :exec
DELETE FROM paper_items WHERE paper_id = $1
`

func (q *Queries) DeletePaperItems(ctx context.Context, paperID string) error {
	_, err := q.db.Exec(ctx, deletePaperItems, paperID)
	return err
}

const getPaperByID = `-- name: GetPaperByID :one
SELECT id, title, subtitle, school_name, exam_name, subject, duration_min,
  total_score, description, status, instructions, footer_text, header_json, layout_json,
  created_at, updated_at, deleted_at
FROM papers
WHERE id = $1
`

func (q *Queries) GetPaperByID(ctx context.Context, id string) (Paper, error) {
	row := q.db.QueryRow(ctx, getPaperByID, id)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.SchoolName,
		&i.ExamName,
		&i.Subject,
		&i.DurationMin,
		&i.TotalScore,
		&i.Description,
		&i.Status,
		&i.Instructions,
		&i.FooterText,
		&i.HeaderJson,
		&i.LayoutJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaperItems = `-- name: GetPaperItems :many
SELECT id, paper_id, problem_id, order_index, score, image_position, blank_lines
FROM paper_items
WHERE paper_id = $1
ORDER BY order_index
`

func (q *Queries) GetPaperItems(ctx context.Context, paperID string) ([]PaperItem, error) {
	rows, err := q.db.Query(ctx, getPaperItems, paperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaperItem
	for rows.Next() {
		var i PaperItem
		if err := rows.Scan(
			&i.ID,
			&i.PaperID,
			&i.ProblemID,
			&i.OrderIndex,
			&i.Score,
			&i.ImagePosition,
			&i.BlankLines,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeletePaper = `-- name: HardDeletePaper :exec
DELETE FROM papers WHERE id = $1
`

func (q *Queries) HardDeletePaper(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, hardDeletePaper, id)
	return err
}

const insertPaper = `-- name: InsertPaper :one
INSERT INTO papers (
  id, title, subtitle, school_name, exam_name, subject, duration_min,
  total_score, description, status, instructions, footer_text, header_json, layout_json,
  created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12, $13, $14,
  $15, $16
)
RETURNING id, title, subtitle, school_name, exam_name, subject, duration_min,
  total_score, description, status, instructions, footer_text, header_json, layout_json,
  created_at, updated_at, deleted_at
`

type InsertPaperParams struct {
	ID           string
	Title        string
	Subtitle     pgtype.Text
	SchoolName   pgtype.Text
	ExamName     pgtype.Text
	Subject      pgtype.Text
	DurationMin  pgtype.Int4
	TotalScore   pgtype.Numeric
	Description  pgtype.Text
	Status       string
	Instructions pgtype.Text
	FooterText   pgtype.Text
	HeaderJson   []byte
	LayoutJson   []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertPaper(ctx context.Context, arg InsertPaperParams) (Paper, error) {
	row := q.db.QueryRow(ctx, insertPaper,
		arg.ID,
		arg.Title,
		arg.Subtitle,
		arg.SchoolName,
		arg.ExamName,
		arg.Subject,
		arg.DurationMin,
		arg.TotalScore,
		arg.Description,
		arg.Status,
		arg.Instructions,
		arg.FooterText,
		arg.HeaderJson,
		arg.LayoutJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.SchoolName,
		&i.ExamName,
		&i.Subject,
		&i.DurationMin,
		&i.TotalScore,
		&i.Description,
		&i.Status,
		&i.Instructions,
		&i.FooterText,
		&i.HeaderJson,
		&i.LayoutJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertPaperItem = `-- name: InsertPaperItem :exec
INSERT INTO paper_items (id, paper_id, problem_id, order_index, score, image_position, blank_lines)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPaperItemParams struct {
	ID            string
	PaperID       string
	ProblemID     string
	OrderIndex    int32
	Score         pgtype.Numeric
	ImagePosition pgtype.Text
	BlankLines    int32
}

func (q *Queries) InsertPaperItem(ctx context.Context, arg InsertPaperItemParams) error {
	_, err := q.db.Exec(ctx, insertPaperItem,
		arg.ID,
		arg.PaperID,
		arg.ProblemID,
		arg.OrderIndex,
		arg.Score,
		arg.ImagePosition,
		arg.BlankLines,
	)
	return err
}

const listPapers = `-- name: ListPapers :many
SELECT id, title, subtitle, school_name, exam_name, subject, duration_min,
  total_score, description, status, instructions, footer_text, header_json, layout_json,
  created_at, updated_at, deleted_at
FROM papers
WHERE ($1::boolean = true OR deleted_at IS NULL)
ORDER BY updated_at DESC
`

func (q *Queries) ListPapers(ctx context.Context, dollar_1 bool) ([]Paper, error) {
	rows, err := q.db.Query(ctx, listPapers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Paper
	for rows.Next() {
		var i Paper
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.SchoolName,
			&i.ExamName,
			&i.Subject,
			&i.DurationMin,
			&i.TotalScore,
			&i.Description,
			&i.Status,
			&i.Instructions,
			&i.FooterText,
			&i.HeaderJson,
			&i.LayoutJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePaper = `-- name: RestorePaper :exec
UPDATE papers SET deleted_at = NULL WHERE id = $1
`

func (q *Queries) RestorePaper(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, restorePaper, id)
	return err
}

const softDeletePaper = `-- name: SoftDeletePaper :exec
UPDATE papers SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeletePaper(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeletePaper, id)
	return err
}

const updatePaper = `-- name: UpdatePaper :one
UPDATE papers SET
  title = $2,
  subtitle = $3,
  school_name = $4,
  exam_name = $5,
  subject = $6,
  duration_min = $7,
  total_score = $8,
  description = $9,
  status = $10,
  instructions = $11,
  footer_text = $12,
  header_json = $13,
  layout_json = $14,
  updated_at = $15
WHERE id = $1
RETURNING id, title, subtitle, school_name, exam_name, subject, duration_min,
  total_score, description, status, instructions, footer_text, header_json, layout_json,
  created_at, updated_at, deleted_at
`

type UpdatePaperParams struct {
	ID           string
	Title        string
	Subtitle     pgtype.Text
	SchoolName   pgtype.Text
	ExamName     pgtype.Text
	Subject      pgtype.Text
	DurationMin  pgtype.Int4
	TotalScore   pgtype.Numeric
	Description  pgtype.Text
	Status       string
	Instructions pgtype.Text
	FooterText   pgtype.Text
	HeaderJson   []byte
	LayoutJson   []byte
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdatePaper(ctx context.Context, arg UpdatePaperParams) (Paper, error) {
	row := q.db.QueryRow(ctx, updatePaper,
		arg.ID,
		arg.Title,
		arg.Subtitle,
		arg.SchoolName,
		arg.ExamName,
		arg.Subject,
		arg.DurationMin,
		arg.TotalScore,
		arg.Description,
		arg.Status,
		arg.Instructions,
		arg.FooterText,
		arg.HeaderJson,
		arg.LayoutJson,
		arg.UpdatedAt,
	)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.SchoolName,
		&i.ExamName,
		&i.Subject,
		&i.DurationMin,
		&i.TotalScore,
		&i.Description,
		&i.Status,
		&i.Instructions,
		&i.FooterText,
		&i.HeaderJson,
		&i.LayoutJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
