// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: problems.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProblems = `-- name: CountProblems :one
SELECT count(*) FROM problems
WHERE ($1::boolean = true OR deleted_at IS NULL)
`

func (q *Queries) CountProblems(ctx context.Context, dollar_1 bool) (int64, error) {
	row := q.db.QueryRow(ctx, countProblems, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProblemImages = `-- name: DeleteProblemImages :exec
DELETE FROM problem_images WHERE problem_id = $1
`

func (q *Queries) DeleteProblemImages(ctx context.Context, problemID string) error {
	_, err := q.db.Exec(ctx, deleteProblemImages, problemID)
	return err
}

const deleteProblemTags = `-- name: DeleteProblemTags :exec
DELETE FROM problem_tags WHERE problem_id = $1
`

func (q *Queries) DeleteProblemTags(ctx context.Context, problemID string) error {
	_, err := q.db.Exec(ctx, deleteProblemTags, problemID)
	return err
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, code, latex, answer_latex, solution_latex, problem_type, difficulty,
  subjective_score, subject, grade, source, notes, search_tsv::text AS search_tsv, formula_tokens, formula_tsv::text AS formula_tsv,
  version, created_at, updated_at, deleted_at
FROM problems
WHERE id = $1
`

type GetProblemByIDRow struct {
	ID              string
	Code            string
	Latex           string
	AnswerLatex     pgtype.Text
	SolutionLatex   pgtype.Text
	ProblemType     string
	Difficulty      string
	SubjectiveScore pgtype.Numeric
	Subject         pgtype.Text
	Grade           pgtype.Text
	Source          pgtype.Text
	Notes           pgtype.Text
	SearchTsv       string
	FormulaTokens   pgtype.Text
	FormulaTsv      string
	Version         int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

func (q *Queries) GetProblemByID(ctx context.Context, id string) (GetProblemByIDRow, error) {
	row := q.db.QueryRow(ctx, getProblemByID, id)
	var i GetProblemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Latex,
		&i.AnswerLatex,
		&i.SolutionLatex,
		&i.ProblemType,
		&i.Difficulty,
		&i.SubjectiveScore,
		&i.Subject,
		&i.Grade,
		&i.Source,
		&i.Notes,
		&i.SearchTsv,
		&i.FormulaTokens,
		&i.FormulaTsv,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProblemImageIDs = `-- name: GetProblemImageIDs :many
SELECT image_id FROM problem_images WHERE problem_id = $1 ORDER BY order_index
`

func (q *Queries) GetProblemImageIDs(ctx context.Context, problemID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getProblemImageIDs, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_id string
		if err := rows.Scan(&image_id); err != nil {
			return nil, err
		}
		items = append(items, image_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblemTagIDs = `-- name: GetProblemTagIDs :many
SELECT tag_id FROM problem_tags WHERE problem_id = $1
`

func (q *Queries) GetProblemTagIDs(ctx context.Context, problemID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getProblemTagIDs, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag_id string
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblemVersion = `-- name: GetProblemVersion :one
SELECT id, problem_id, version, snapshot, created_at
FROM problem_versions
WHERE problem_id = $1 AND version = $2
`

type GetProblemVersionParams struct {
	ProblemID string
	Version   int32
}

func (q *Queries) GetProblemVersion(ctx context.Context, arg GetProblemVersionParams) (ProblemVersion, error) {
	row := q.db.QueryRow(ctx, getProblemVersion, arg.ProblemID, arg.Version)
	var i ProblemVersion
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Version,
		&i.Snapshot,
		&i.CreatedAt,
	)
	return i, err
}

const getProblemVersions = `-- name: GetProblemVersions :many
SELECT id, problem_id, version, snapshot, created_at
FROM problem_versions
WHERE problem_id = $1
ORDER BY version DESC
`

func (q *Queries) GetProblemVersions(ctx context.Context, problemID string) ([]ProblemVersion, error) {
	rows, err := q.db.Query(ctx, getProblemVersions, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProblemVersion
	for rows.Next() {
		var i ProblemVersion
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Version,
			&i.Snapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblemsByIDs = `-- name: GetProblemsByIDs :many
SELECT id, code, latex, answer_latex, solution_latex, problem_type, difficulty,
  subjective_score, subject, grade, source, notes, search_tsv::text AS search_tsv, formula_tokens, formula_tsv::text AS formula_tsv,
  version, created_at, updated_at, deleted_at
FROM problems
WHERE id = ANY($1::text[])
ORDER BY updated_at DESC
`

type GetProblemsByIDsRow struct {
	ID              string
	Code            string
	Latex           string
	AnswerLatex     pgtype.Text
	SolutionLatex   pgtype.Text
	ProblemType     string
	Difficulty      string
	SubjectiveScore pgtype.Numeric
	Subject         pgtype.Text
	Grade           pgtype.Text
	Source          pgtype.Text
	Notes           pgtype.Text
	SearchTsv       string
	FormulaTokens   pgtype.Text
	FormulaTsv      string
	Version         int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

func (q *Queries) GetProblemsByIDs(ctx context.Context, dollar_1 []string) ([]GetProblemsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getProblemsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProblemsByIDsRow
	for rows.Next() {
		var i GetProblemsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Latex,
			&i.AnswerLatex,
			&i.SolutionLatex,
			&i.ProblemType,
			&i.Difficulty,
			&i.SubjectiveScore,
			&i.Subject,
			&i.Grade,
			&i.Source,
			&i.Notes,
			&i.SearchTsv,
			&i.FormulaTokens,
			&i.FormulaTsv,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteProblem = `-- name: HardDeleteProblem :exec
DELETE FROM problems WHERE id = $1
`

func (q *Queries) HardDeleteProblem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, hardDeleteProblem, id)
	return err
}

const incrementCodeCounter = `-- name: IncrementCodeCounter :one
INSERT INTO problem_code_counters (year, current_serial, updated_at)
VALUES ($1, 1, now())
ON CONFLICT (year) DO UPDATE
  SET current_serial = problem_code_counters.current_serial + 1,
      updated_at = now()
RETURNING current_serial
`

func (q *Queries) IncrementCodeCounter(ctx context.Context, year int32) (int32, error) {
	row := q.db.QueryRow(ctx, incrementCodeCounter, year)
	var current_serial int32
	err := row.Scan(&current_serial)
	return current_serial, err
}

const incrementProblemVersion = `-- name: IncrementProblemVersion :exec
UPDATE problems SET version = version + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) IncrementProblemVersion(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementProblemVersion, id)
	return err
}

const insertProblem = `-- name: InsertProblem :one
INSERT INTO problems (
  id, code, latex, answer_latex, solution_latex, problem_type, difficulty,
  subjective_score, subject, grade, source, notes, formula_tokens, version,
  created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12, $13, $14,
  $15, $16
)
RETURNING id, code, latex, answer_latex, solution_latex, problem_type, difficulty,
  subjective_score, subject, grade, source, notes, search_tsv::text AS search_tsv, formula_tokens, formula_tsv::text AS formula_tsv,
  version, created_at, updated_at, deleted_at
`

type InsertProblemParams struct {
	ID              string
	Code            string
	Latex           string
	AnswerLatex     pgtype.Text
	SolutionLatex   pgtype.Text
	ProblemType     string
	Difficulty      string
	SubjectiveScore pgtype.Numeric
	Subject         pgtype.Text
	Grade           pgtype.Text
	Source          pgtype.Text
	Notes           pgtype.Text
	FormulaTokens   pgtype.Text
	Version         int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type InsertProblemRow struct {
	ID              string
	Code            string
	Latex           string
	AnswerLatex     pgtype.Text
	SolutionLatex   pgtype.Text
	ProblemType     string
	Difficulty      string
	SubjectiveScore pgtype.Numeric
	Subject         pgtype.Text
	Grade           pgtype.Text
	Source          pgtype.Text
	Notes           pgtype.Text
	SearchTsv       string
	FormulaTokens   pgtype.Text
	FormulaTsv      string
	Version         int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

func (q *Queries) InsertProblem(ctx context.Context, arg InsertProblemParams) (InsertProblemRow, error) {
	row := q.db.QueryRow(ctx, insertProblem,
		arg.ID,
		arg.Code,
		arg.Latex,
		arg.AnswerLatex,
		arg.SolutionLatex,
		arg.ProblemType,
		arg.Difficulty,
		arg.SubjectiveScore,
		arg.Subject,
		arg.Grade,
		arg.Source,
		arg.Notes,
		arg.FormulaTokens,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i InsertProblemRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Latex,
		&i.AnswerLatex,
		&i.SolutionLatex,
		&i.ProblemType,
		&i.Difficulty,
		&i.SubjectiveScore,
		&i.Subject,
		&i.Grade,
		&i.Source,
		&i.Notes,
		&i.SearchTsv,
		&i.FormulaTokens,
		&i.FormulaTsv,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertProblemImage = `-- name: InsertProblemImage :exec
INSERT INTO problem_images (problem_id, image_id, order_index) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertProblemImageParams struct {
	ProblemID  string
	ImageID    string
	OrderIndex int32
}

func (q *Queries) InsertProblemImage(ctx context.Context, arg InsertProblemImageParams) error {
	_, err := q.db.Exec(ctx, insertProblemImage, arg.ProblemID, arg.ImageID, arg.OrderIndex)
	return err
}

const insertProblemTag = `-- name: InsertProblemTag :exec
INSERT INTO problem_tags (problem_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertProblemTagParams struct {
	ProblemID string
	TagID     string
}

func (q *Queries) InsertProblemTag(ctx context.Context, arg InsertProblemTagParams) error {
	_, err := q.db.Exec(ctx, insertProblemTag, arg.ProblemID, arg.TagID)
	return err
}

const insertProblemVersion = `-- name: InsertProblemVersion :exec
INSERT INTO problem_versions (id, problem_id, version, snapshot, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertProblemVersionParams struct {
	ID        string
	ProblemID string
	Version   int32
	Snapshot  []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertProblemVersion(ctx context.Context, arg InsertProblemVersionParams) error {
	_, err := q.db.Exec(ctx, insertProblemVersion,
		arg.ID,
		arg.ProblemID,
		arg.Version,
		arg.Snapshot,
		arg.CreatedAt,
	)
	return err
}

const listProblems = `-- name: ListProblems :many
SELECT id, code, latex, answer_latex, solution_latex, problem_type, difficulty,
  subjective_score, subject, grade, source, notes, search_tsv::text AS search_tsv, formula_tokens, formula_tsv::text AS formula_tsv,
  version, created_at, updated_at, deleted_at
FROM problems
WHERE ($1::boolean = true OR deleted_at IS NULL)
ORDER BY updated_at DESC
`

type ListProblemsRow struct {
	ID              string
	Code            string
	Latex           string
	AnswerLatex     pgtype.Text
	SolutionLatex   pgtype.Text
	ProblemType     string
	Difficulty      string
	SubjectiveScore pgtype.Numeric
	Subject         pgtype.Text
	Grade           pgtype.Text
	Source          pgtype.Text
	Notes           pgtype.Text
	SearchTsv       string
	FormulaTokens   pgtype.Text
	FormulaTsv      string
	Version         int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

func (q *Queries) ListProblems(ctx context.Context, dollar_1 bool) ([]ListProblemsRow, error) {
	rows, err := q.db.Query(ctx, listProblems, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProblemsRow
	for rows.Next() {
		var i ListProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Latex,
			&i.AnswerLatex,
			&i.SolutionLatex,
			&i.ProblemType,
			&i.Difficulty,
			&i.SubjectiveScore,
			&i.Subject,
			&i.Grade,
			&i.Source,
			&i.Notes,
			&i.SearchTsv,
			&i.FormulaTokens,
			&i.FormulaTsv,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProblem = `-- name: RestoreProblem :exec
UPDATE problems SET deleted_at = NULL WHERE id = $1
`

func (q *Queries) RestoreProblem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, restoreProblem, id)
	return err
}

const softDeleteProblem = `-- name: SoftDeleteProblem :exec
UPDATE problems SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteProblem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteProblem, id)
	return err
}

const updateProblem = `-- name: UpdateProblem :one
UPDATE problems SET
  latex = $2,
  answer_latex = $3,
  solution_latex = $4,
  problem_type = $5,
  difficulty = $6,
  subjective_score = $7,
  subject = $8,
  grade = $9,
  source = $10,
  notes = $11,
  formula_tokens = $12,
  version = $13,
  updated_at = $14
WHERE id = $1
RETURNING id, code, latex, answer_latex, solution_latex, problem_type, difficulty,
  subjective_score, subject, grade, source, notes, search_tsv::text AS search_tsv, formula_tokens, formula_tsv::text AS formula_tsv,
  version, created_at, updated_at, deleted_at
`

type UpdateProblemParams struct {
	ID              string
	Latex           string
	AnswerLatex     pgtype.Text
	SolutionLatex   pgtype.Text
	ProblemType     string
	Difficulty      string
	SubjectiveScore pgtype.Numeric
	Subject         pgtype.Text
	Grade           pgtype.Text
	Source          pgtype.Text
	Notes           pgtype.Text
	FormulaTokens   pgtype.Text
	Version         int32
	UpdatedAt       pgtype.Timestamptz
}

type UpdateProblemRow struct {
	ID              string
	Code            string
	Latex           string
	AnswerLatex     pgtype.Text
	SolutionLatex   pgtype.Text
	ProblemType     string
	Difficulty      string
	SubjectiveScore pgtype.Numeric
	Subject         pgtype.Text
	Grade           pgtype.Text
	Source          pgtype.Text
	Notes           pgtype.Text
	SearchTsv       string
	FormulaTokens   pgtype.Text
	FormulaTsv      string
	Version         int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) (UpdateProblemRow, error) {
	row := q.db.QueryRow(ctx, updateProblem,
		arg.ID,
		arg.Latex,
		arg.AnswerLatex,
		arg.SolutionLatex,
		arg.ProblemType,
		arg.Difficulty,
		arg.SubjectiveScore,
		arg.Subject,
		arg.Grade,
		arg.Source,
		arg.Notes,
		arg.FormulaTokens,
		arg.Version,
		arg.UpdatedAt,
	)
	var i UpdateProblemRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Latex,
		&i.AnswerLatex,
		&i.SolutionLatex,
		&i.ProblemType,
		&i.Difficulty,
		&i.SubjectiveScore,
		&i.Subject,
		&i.Grade,
		&i.Source,
		&i.Notes,
		&i.SearchTsv,
		&i.FormulaTokens,
		&i.FormulaTsv,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
