// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: searches.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSavedSearch = `-- name: CreateSavedSearch :one
INSERT INTO saved_searches (id, name, query, filters, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, query, filters, created_at
`

type CreateSavedSearchParams struct {
	ID        string
	Name      string
	Query     pgtype.Text
	Filters   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateSavedSearch(ctx context.Context, arg CreateSavedSearchParams) (SavedSearch, error) {
	row := q.db.QueryRow(ctx, createSavedSearch,
		arg.ID,
		arg.Name,
		arg.Query,
		arg.Filters,
		arg.CreatedAt,
	)
	var i SavedSearch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Query,
		&i.Filters,
		&i.CreatedAt,
	)
	return i, err
}

const createSearchHistory = `-- name: CreateSearchHistory :one
INSERT INTO search_history (id, query, filters, result_count, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, query, filters, result_count, created_at
`

type CreateSearchHistoryParams struct {
	ID          string
	Query       string
	Filters     []byte
	ResultCount int32
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateSearchHistory(ctx context.Context, arg CreateSearchHistoryParams) (SearchHistory, error) {
	row := q.db.QueryRow(ctx, createSearchHistory,
		arg.ID,
		arg.Query,
		arg.Filters,
		arg.ResultCount,
		arg.CreatedAt,
	)
	var i SearchHistory
	err := row.Scan(
		&i.ID,
		&i.Query,
		&i.Filters,
		&i.ResultCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSavedSearch = `-- name: DeleteSavedSearch :exec
DELETE FROM saved_searches WHERE id = $1
`

func (q *Queries) DeleteSavedSearch(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSavedSearch, id)
	return err
}

const deleteSearchHistory = `-- name: DeleteSearchHistory :exec
DELETE FROM search_history WHERE id = $1
`

func (q *Queries) DeleteSearchHistory(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSearchHistory, id)
	return err
}

const listSavedSearches = `-- name: ListSavedSearches :many
SELECT id, name, query, filters, created_at
FROM saved_searches
ORDER BY created_at DESC
`

func (q *Queries) ListSavedSearches(ctx context.Context) ([]SavedSearch, error) {
	rows, err := q.db.Query(ctx, listSavedSearches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedSearch
	for rows.Next() {
		var i SavedSearch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Query,
			&i.Filters,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearchHistory = `-- name: ListSearchHistory :many
SELECT id, query, filters, result_count, created_at
FROM search_history
ORDER BY created_at DESC
LIMIT 20
`

func (q *Queries) ListSearchHistory(ctx context.Context) ([]SearchHistory, error) {
	rows, err := q.db.Query(ctx, listSearchHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchHistory
	for rows.Next() {
		var i SearchHistory
		if err := rows.Scan(
			&i.ID,
			&i.Query,
			&i.Filters,
			&i.ResultCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
