// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: tags.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTagProblems = `-- name: CountTagProblems :one
SELECT count(*) FROM problem_tags WHERE tag_id = $1
`

func (q *Queries) CountTagProblems(ctx context.Context, tagID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTagProblems, tagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, category, color, description, created_at, updated_at
FROM tags
WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :one
INSERT INTO tags (id, name, category, color, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, category, color, description, created_at, updated_at
`

type InsertTagParams struct {
	ID          string
	Name        string
	Category    string
	Color       string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, insertTag,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Color,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, category, color, description, created_at, updated_at
FROM tags
ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImageTagsForMerge = `-- name: UpdateImageTagsForMerge :exec
UPDATE image_tags it SET tag_id = $1
WHERE it.tag_id = $2
  AND it.image_id NOT IN (
    SELECT it2.image_id FROM image_tags it2 WHERE it2.tag_id = $1
  )
`

type UpdateImageTagsForMergeParams struct {
	TagID   string
	TagID_2 string
}

func (q *Queries) UpdateImageTagsForMerge(ctx context.Context, arg UpdateImageTagsForMergeParams) error {
	_, err := q.db.Exec(ctx, updateImageTagsForMerge, arg.TagID, arg.TagID_2)
	return err
}

const updateProblemTagsForMerge = `-- name: UpdateProblemTagsForMerge :exec
UPDATE problem_tags pt SET tag_id = $1
WHERE pt.tag_id = $2
  AND pt.problem_id NOT IN (
    SELECT pt2.problem_id FROM problem_tags pt2 WHERE pt2.tag_id = $1
  )
`

type UpdateProblemTagsForMergeParams struct {
	TagID   string
	TagID_2 string
}

func (q *Queries) UpdateProblemTagsForMerge(ctx context.Context, arg UpdateProblemTagsForMergeParams) error {
	_, err := q.db.Exec(ctx, updateProblemTagsForMerge, arg.TagID, arg.TagID_2)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET
  name = $2,
  category = $3,
  color = $4,
  description = $5,
  updated_at = $6
WHERE id = $1
RETURNING id, name, category, color, description, created_at, updated_at
`

type UpdateTagParams struct {
	ID          string
	Name        string
	Category    string
	Color       string
	Description pgtype.Text
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Color,
		arg.Description,
		arg.UpdatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
